export const product = [
  {
    id: "a1",
    source: "/TerbaruProduct/Lemon.png",
    value: "Lemon",
    price: +20000,
    unit: "Kg",
    rate: +4.3,
    sold: +100,
    category: "Buah",
  },
  {
    id: "a2",
    source: "/TerbaruProduct/BibitPinang.png",
    value: "Bibit Pinang",
    price: +3500,
    unit: "Item",
    rate: +3.5,
    sold: +1000,
    category: "Bibit",
  },
  {
    id: "a3",
    source: "/TerbaruProduct/Mengkudu.png",
    value: "Mengkudu",
    price: +6400,
    unit: "Kg",
    rate: +4.1,
    sold: +71,
    category: "Buah",
  },
  {
    id: "a4",
    source: "/TerbaruProduct/Kunyit.png",
    value: "Kunyit",
    price: +35000,
    unit: "Kg",
    rate: +3.9,
    sold: +23,
    category: "Buah",
  },
  {
    id: "a5",
    source: "/PopulerProduct/PupukNonSubsidi.png",
    value: "Pupuk Non-Subsidi",
    price: +200000,
    unit: "Sak",
    rate: +4.5,
    sold: +40,
    category: "Pupuk",
  },
  {
    id: "a6",
    source: "/PopulerProduct/CengkehKering.png",
    value: "Cengkeh Kering",
    price: +140000,
    unit: "Kg",
    rate: +4.0,
    sold: +20,
    category: "Buah",
  },
  {
    id: "a7",
    source: "/PopulerProduct/JagungPipil.png",
    value: "Jagung Pipil",
    price: +6000,
    unit: "Kg",
    rate: +4.2,
    sold: +40,
    category: "Buah",
  },
  {
    id: "a8",
    source: "/PopulerProduct/KedelaiNonGMO.png",
    value: "Kedelai Non GMO",
    price: +10000,
    unit: "Kg",
    rate: +4.8,
    sold: +80,
    category: "Buah",
  },
  {
    id: "a9",
    source: "/Product/Stoberi.png",
    value: "Buah Stoberi",
    price: +50000,
    unit: "Kg",
    rate: +4,
    sold: +10,
    category: "Buah",
  },
  {
    id: "a10",
    source: "/Product/PisangCavendish.jpg",
    value: "Pisang Cavendish",
    price: +15000,
    unit: "Kg",
    rate: +4.5,
    sold: +20,
    category: "Buah",
  },
  {
    id: "a11",
    source: "/Product/Jeruk.png",
    value: "Jeruk Lokal",
    price: +10000,
    unit: "Kg",
    rate: +5,
    sold: +5,
    category: "Buah",
  },
  {
    id: "a12",
    source: "/Product/BuahNaga.png",
    value: "Buah Naga",
    price: +20000,
    unit: "Kg",
    rate: +4.2,
    sold: +8,
    category: "Buah",
  },
  {
    id: "a13",
    source: "/Product/JambuKristal.png",
    value: "Jambu Kristal",
    price: +14000,
    unit: "Kg",
    rate: +4.6,
    sold: +4,
    category: "Buah",
  },
  {
    id: "a14",
    source: "/Product/PohonBakungAmarilis.png",
    value: "Bibit Pohon Bakung Amarilis",
    price: +7500,
    unit: "Bibit",
    rate: +3.9,
    sold: +20,
    category: "Bibit",
  },
  {
    id: "a15",
    source: "/Product/PohonPalemKuning.jpg",
    value: "Bibit Pohon Palem Kuning",
    price: +300000,
    unit: "Biji",
    rate: +4.5,
    sold: +3,
    category: "Bibit",
  },
  {
    id: "a16",
    source: "/Product/RumputGajah.png",
    value: "Bibit Rumput Gajah",
    price: +15000,
    unit: "Bibit",
    rate: +3.5,
    sold: +1,
    category: "Bibit",
  },
  {
    id: "a17",
    source: "/Product/PohonPucukMerah.png",
    value: "Bibit Pohon Pucuk Merah",
    price: +35000,
    unit: "Bibit",
    rate: +4,
    sold: +30,
    category: "Bibit",
  },
  {
    id: "a18",
    source: "/Product/PohonTrembesiAmbon.png",
    value: "Bibit Pohon Trembesi Ambon",
    price: +200000,
    unit: "Bibit",
    rate: +4.3,
    sold: +7,
    category: "Bibit",
  },
  {
    id: "a19",
    source: "/Product/SekopTamankayu.jpg",
    value: "Sekop Taman Kayu",
    price: +150000,
    unit: "Barang",
    rate: +4.7,
    sold: +5,
    category: "Peralatan",
  },
  {
    id: "a20",
    source: "/Product/SarungTanganBerkebun.jpg",
    value: "Sarung Tangan Berkebun",
    price: +35000,
    unit: "Barang",
    rate: +5,
    sold: +2,
    category: "Peralatan",
  },
  {
    id: "a21",
    source: "/Product/SabitPadi.jpg",
    value: "Sabit Padi",
    price: +27000,
    unit: "Barang",
    rate: +4.7,
    sold: +36,
    category: "Peralatan",
  },
  {
    id: "a22",
    source: "/Product/SekopMini.jpg",
    value: "Sekop Mini",
    price: +13000,
    unit: "Barang",
    rate: +4.9,
    sold: +21,
    category: "Peralatan",
  },
  {
    id: "a23",
    source: "/Product/GuntingDahanRanting.jpg",
    value: "Gunting Dahan Ranting",
    price: +50000,
    unit: "Barang",
    rate: +4.7,
    sold: +17,
    category: "Peralatan",
  },
  {
    id: "a24",
    source: "/Product/Pacul.jpg",
    value: "Pacul",
    price: +125000,
    unit: "Barang",
    rate: +4,
    sold: +6,
    category: "Peralatan",
  },
];
