export const product = [
  {
    id: "a1",
    source: "/TerbaruProduct/Lemon.png",
    value: "Lemon",
    price: +20000,
    unit: "Kg",
    rate: +4.3,
    sold: +100,
    category: "Buah",
  },
  {
    id: "a2",
    source: "/TerbaruProduct/BibitPinang.png",
    value: "Bibit Pinang",
    price: +3500,
    unit: "Item",
    rate: +3.5,
    sold: +1000,
    category: "Bibit",
  },
  {
    id: "a3",
    source: "/TerbaruProduct/Mengkudu.png",
    value: "Mengkudu",
    price: +6400,
    unit: "Kg",
    rate: +4.1,
    sold: +71,
    category: "Buah",
  },
  {
    id: "a4",
    source: "/TerbaruProduct/Kunyit.png",
    value: "Kunyit",
    price: +35000,
    unit: "Kg",
    rate: +3.9,
    sold: +23,
    category: "Buah",
  },
  {
    id: "a5",
    source: "/PopulerProduct/PupukNonSubsidi.png",
    value: "Pupuk Non-Subsidi",
    price: +200000,
    unit: "Sak",
    rate: +4.5,
    sold: +40,
    category: "Pupuk",
  },
  {
    id: "a6",
    source: "/PopulerProduct/CengkehKering.png",
    value: "Cengkeh Kering",
    price: +140000,
    unit: "Kg",
    rate: +4.0,
    sold: +20,
    category: "Buah",
  },
  {
    id: "a7",
    source: "/PopulerProduct/JagungPipil.png",
    value: "Jagung Pipil",
    price: +6000,
    unit: "Kg",
    rate: +4.2,
    sold: +40,
    category: "Buah",
  },
  {
    id: "a8",
    source: "/PopulerProduct/KedelaiNonGMO.png",
    value: "Kedelai Non GMO",
    price: +10000,
    unit: "Kg",
    rate: +4.8,
    sold: +80,
    category: "Buah",
  },
];
